### ISSUE TITLE
eGPU not recognized

### ISSUE THREAD

**Issue by cengizkursat** [mayankk2308/kryptonite#15]
### Problem Description

I have a Late 2011 17 Inch MacBook Pro with macOS 11.5.2 via OCLP and a Razer Core X. I followed the instructions of basic installation (not manual installation). However, as it can be seen in the screenshots, even if my eGPU is detected as a PCI device, it is not detected as a GPU as it should have been. I provided logs and screenshots but if the information is not enough, I will happily provide more if asked. Also, SIP and FileVault is off.

### Logs
[Lilu_1.5.3_20.6.txt](https://github.com/mayankk2308/kryptonite/files/7088537/Lilu_1.5.3_20.6.txt)
[opencore-2021-09-01-052512.txt](https://github.com/mayankk2308/kryptonite/files/7088538/opencore-2021-09-01-052512.txt)

### Screenshots

![Screen Shot 2021-09-01 at 08 27 07](https://user-images.githubusercontent.com/56599217/131618289-90a979c8-214d-4b85-bd55-6deec408ff8a.png)
![Screen Shot 2021-09-01 at 08 27 48](https://user-images.githubusercontent.com/56599217/131618290-3abd4cf3-05ea-4987-9dae-a20321173da0.png)
![Screen Shot 2021-09-01 at 08 34 10](https://user-images.githubusercontent.com/56599217/131618293-f939cad2-ec3d-4ba6-a24b-5f1cc65f4bb2.png)

**Comment by PachaMama666** [comment]
SIMILAR PROBLEM

MacMini Late 2014, Big Sur 11.5.2, Razor Core X, Radeon Sapphire Pulse RX580,
But instead of the PCI, I got the Graphics/Display recognition, without any specific infos of the GPU. Still black screen. Any suggestions?
Didn`t found the kext debug file either. No "var"folder


![Bildschirmfoto 2021-09-01 um 10 47 48](https://user-images.githubusercontent.com/89904871/131641480-ae4286d7-416d-409b-9d43-a1f5d2af0e3e.png)
[opencore-2021-09-01-083947.txt](https://github.com/mayankk2308/kryptonite/files/7089692/opencore-2021-09-01-083947.txt)

**Comment by mayankk2308** [comment]
Compatibility with other OCLP patches is not guaranteed. See:
- https://github.com/dortania/OpenCore-Legacy-Patcher/issues/336
- https://egpu.io/forums/mac-setup/kryptonite-tb1-2-mac-egpu-support-with-filevault-sip-and-art-enabled/paged/3/#post-96107

These issues are out of scope for this project at the moment.
